# Storage options to save the skymines.
storage:
  type: SQLite # Options: PostgreSQL, MySQL, SQLite
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: ""

# Various options to change the different behaviors of the plugin.
option:
  skymine:
    # Maximum amount of skymines per player.
    max-per-player: 10
    # If true, skymines can be placed over transparent blocks (grass, flowers, etc.)
    # This does not include chests.
    override-transparent-blocks: true
    # If true, players can shift-left-click their mine border to instantly teleport to its home.
    fast-home: true
    # Maximum amount of blocks a player can be from the skymine to set its home.
    sethome-distance: 5
    # If true, skymine creation ignores physics, allowing them to be created much faster.
    # If you are having any problems with physics/lighting due to skymines, feel free to disable this.
    ignore-physics: true
  token:
    # If true, players can no longer drop their skymine token.
    prevent-drop: true
  reset:
    # Should a mine reset replace blocks (inside the mine)? If false, only replaces AIR.
    replace-blocks: false
    # Should all players inside the mine be teleported to the mine's home on reset?
    teleport-home: true
    # Should the mine be reset when you upgrade it?
    on-upgrade: true
  cooldown:
    # Cooldown (in seconds) players have to wait if they picked up a skymine.
    # Additional option: 'dynamic' - the cooldown to place it back down would be the current time left to reset the mine.
    pickup-cooldown: dynamic
  hologram:
    # Enables holograms for every placed skymine.
    toggle: true
    # The hologram lines. Placeholders will auto-update if they change.
    # Additional placeholder: {reset-cooldown}
    lines:
      - "&7[&e&lSkyMine&7] &8- &a{label}"
      - "&9Owner: &e{player}"
      - "&9Reset Timer: &c{time}"

misc:
  # Allows us to collect anonymous data about the plugin.
  enable-metrics: true