# Save your skymines:
save:
  # Options: PostgreSQL, MySQL, SQLite
  type: SQLite
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: ""

# Various options for skymines:
options:
  # Maximum amount of skymines per player.
  max-per-player: 10
  # Should a mine reset replace blocks (inside the mine)? If false, only replaces AIR.
  replace-blocks: false
  # Should the owner of the mine be teleported to the mine's home on reset?
  teleport-home-on-reset: true
  # Should the mine be reset when you upgrade it?
  reset-on-upgrade: true
  # Should the owner of the mine be notified when it can be reset again?
  notify-on-reset-cooldown-finish: true
  # Should a player be notified when they can place skymines again? (see pickup-cooldown below)
  notify-on-pickup-cooldown-finish: true
  # Cooldown (in seconds) players have to wait if they picked up a skymine.
  # Additional option: 'dynamic' - the cooldown to place it back down would be the current time left to reset the mine.
  pickup-cooldown: dynamic
  # Cooldown (in seconds) players have to wait to attempt skymine placement again (for performance reasons).
  placement-cooldown: 10
  # If true, players can no longer drop their skymine token.
  prevent-token-drop: true
  # If true, skymines can be placed over transparent blocks (grass, flowers, etc.)
  # This does not include chests.
  override-transparent-blocks: true
  # If true, players can shift-left-click the mine border to instantly teleport to its home.
  fast-home: true

misc:
  # Allows us to collect anonymous data about the plugin.
  enable-metrics: true