name: SkyMines
main: com.github.colingrime.SkyMines
version: @version@

authors: [Scill]
description: Place mines... IN THE SKY!!
api-version: 1.18
depend: [Vault]
softdepend: [FastAsyncWorldEdit]

commands:
  skymines:
    description: Main command for skymines.
    aliases: [mines, sm]