name: SkyMines
main: com.github.colingrime.SkyMines
version: @version@

authors: [ Scill ]
description: Personal Mines (in the sky!)
api-version: 1.13
depend: [ Vault ]
softdepend: [ FastAsyncWorldEdit ]

commands:
  skymines:
    description: Main command for skymines.
    aliases: [ skymine, sm ]
  skyminesadmin:
    description: Admin section for skymines.
    aliases: [ skymineadmin, smadmin, sma ]