name: Development-Builds
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
      - uses: "actions/upload-artifact@v3"
        with:
          name: "SkyMines"
          path: |
            ./target/SkyMines.jar